import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XMLTree with RSS (version 2.0) feed from a given URL
 * into the corresponding HTML output files.
 *
 * @author Rachel Thoi
 *
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel")
                : "" + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        //Declare variables and get XML subtrees (required for RSS)
        XMLTree titleTree = channel.child(getChildElement(channel, "title"));
        XMLTree linkTree = channel.child(getChildElement(channel, "link"));
        XMLTree descTree = channel.child(getChildElement(channel, "description"));

        //Link is required
        String link = linkTree.child(0).label();

        //Get title (not required)
        String title = "Empty Title";
        if (titleTree.numberOfChildren() > 0) {
            title = titleTree.child(0).label();
        }

        //Get description (not required)
        String desc = "No description";
        if (descTree.numberOfChildren() > 0) {
            desc = descTree.child(0).label();
        }

        //Start printing the html
        out.println("<html>");

        out.println("   <head>");
        out.println("      <title>" + title + "</title>");
        out.println("   </head>");

        out.println("   <body>");

        out.println(
                "      <h1>" + ("<a href=\"" + link + "\">" + title + "</a>") + "</h1>");

        out.println("      <p>" + desc + "</p>");

        out.println("      <table border = \"1\">");

        out.println("         <tr>");
        out.println("            <th>Data</th>");
        out.println("            <th>Source</th>");
        out.println("            <th>News</th>");
        out.println("         </tr>");

    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("      </table>");
        out.println("   </body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        // Initialize the index to -1, which indicates that the tag has not been found yet
        int index = -1;

        // Iterate through the children of the XMLTree
        // Find if the children has a tag
        int i = 0;
        while (i < xml.numberOfChildren() && index == -1) {
            // Verify that child(i) is a tag
            if (xml.child(i).isTag()) {
                // If a child with the specified tag is found, update the index
                if (xml.child(i).label().equals(tag)) {
                    index = i;
                }
            }
            i++;
        }

        // Return the index of the found child, or -1 if not found
        return index;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item")
                : "" + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        //Check if pubDate tag is present and if so get child text node
        // (required if parent present)
        String date = "No date available";
        int dateIndex = getChildElement(item, "pubDate");
        if (dateIndex >= 0) {
            date = item.child(dateIndex).child(0).label();
        }

        // Check if link tag is present and if so get child text node
        // (required if parent is present)
        String link = "";
        int linkIndex = getChildElement(item, "link");
        boolean hasLink = false;
        if (linkIndex >= 0) {
            link = item.child(linkIndex).child(0).label();
            hasLink = true;
        }

        // Initialize title to "No title available"
        String title = "No title available";

        // Check for <title> tag and its text child
        int titleIndex = getChildElement(item, "title");
        if (titleIndex >= 0) {
            XMLTree titleTree = item.child(titleIndex);
            if (titleTree.numberOfChildren() > 0) {
                title = titleTree.child(0).label();
            } else {
                // Check for <description> tag and its text child if <title> is empty
                int descriptionIndex = getChildElement(item, "description");
                if (descriptionIndex >= 0) {
                    XMLTree descriptionTree = item.child(descriptionIndex);
                    if (descriptionTree.numberOfChildren() > 0) {
                        title = descriptionTree.child(0).label();
                    }
                }
            }
        }

        // Check if source tag is present and if so store url and check if child
        // and if there is a child get the text node
        String source = "";
        String sourceLink = "";
        boolean hasSource = false;
        int sourceIndex = getChildElement(item, "source");
        if (sourceIndex >= 0) {
            hasSource = true;
            XMLTree sourceTree = item.child(sourceIndex);
            sourceLink = sourceTree.attributeValue("url");
            if (sourceTree.numberOfChildren() > 0) {
                source = sourceTree.child(0).label();
            } else {
                source = sourceLink;
            }
        }

        // With defined variables, write the html to the file
        out.println("         <tr>");
        out.println("            <td>" + date + "</td>");
        out.println("            <td>");

        //If there is a source link, adjust html output accordingly
        if (hasSource) {
            out.println("               <a href=" + sourceLink + ">" + source + "</a>");
        } else {
            out.println("No source available");
        }
        out.println("            </td>");
        out.println("            <td>");

        //If there is a link, adjust html output accordingly
        if (hasLink) {
            out.println("               <a href=" + link + ">" + title + "</a>");
        } else {
            out.println(title);
        }
        out.println("            </td>");
        out.println("         </tr>");

    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        // Make sure that the given url is valid RSS
        boolean validRSS = false;

        // Create an XMLTree from the given URL
        XMLTree testTree = new XMLTree1(url);
        // Check if the XMLTree is an RSS feed of version 2.0
        if (testTree.label().equals("rss")
                && testTree.attributeValue("version").equals("2.0")) {
            validRSS = true;
        }

        //If valid, RSS print html code to output file
        if (validRSS) {
            // Create a new SimpleWriter for the output file
            SimpleWriter outFile = new SimpleWriter1L("data/" + file);
            // Re-create the XMLTree to process it
            XMLTree tree = new XMLTree1(url);

            // Output the header of the HTML file
            outputHeader(tree.child(0), outFile);

            // Loop through the children of the root element and process each item
            for (int i = 0; i < tree.child(0).numberOfChildren(); i++) {
                if (tree.child(0).child(i).label().equals("item")) {
                    processItem(tree.child(0).child(i), outFile);
                }
            }

            // Output the footer of the HTML file
            outputFooter(outFile);

            // Print a message indicating that data has been written to the file
            out.println("Data has been written to: " + file);

            // Close the output file writer
            outFile.close();

            // Print a message indicating that the URL is not a valid RSS feed
        } else {
            out.println(file + " is not a valid RSS 2.0 feed!");
        }

    }

    /**
     * Main method that prompts user for XML url and html file and writes html
     * to that specified file.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        //Get XMLTree url and file name
        String url = "";
        String fileName = "";

        // Prompt the user to enter the URL of the RSS 2.0 feed
        out.print("Enter the URL of RSS 2.0 Feed: ");
        url = in.nextLine();

        // Prompt the user to enter the name of the output file
        out.print("Enter name of the output file: ");
        fileName = in.nextLine();

        // Process Data
        SimpleWriter fileIndex = new SimpleWriter1L("data/" + fileName + ".html");
        XMLTree mainTree = new XMLTree1(url);

        // Initialize the title variable
        String title = "";

        // Check if the root element has the "title" attribute and get its value
        if (mainTree.hasAttribute("title")) {
            title = mainTree.attributeValue("title");
        } else {
            // Handle the case where the title attribute is missing
            title = "RSS Feed";
        }

        // Get the title attribute from the XMLTree
        String outputURL = "";
        String name = "";
        String file = "";

        // Write the HTML file
        fileIndex.println("<html>");
        fileIndex.println(" <head>");
        fileIndex.println(" <title>" + title + "</title>");
        fileIndex.println(" </head>");
        fileIndex.println(" <body>");
        fileIndex.println(" <h2>" + title + "</h2>");
        fileIndex.println(" <ul>");

        // Process each child element of the main XML tree
        for (int i = 0; i < mainTree.numberOfChildren(); i++) {
            if (mainTree.child(i).label().equals("feed")) {
            
            // Get the attributes of each child element
            outputURL = mainTree.child(i).attributeValue("url");
            name = mainTree.child(i).attributeValue("name");
            file = mainTree.child(i).attributeValue("file");

            // Write a list item to the HTML file
            fileIndex.println(" <li>");
            fileIndex.println(" <a href=\"" + file + "\">" + name + "</a>");
            fileIndex.println(" </li>");

            // Process the RSS feed for each child element
            processFeed(outputURL, file, out);
            }
        }

        // Finish writing the HTML file
        fileIndex.println(" </ul>");
        fileIndex.println(" </body>");
        fileIndex.println("</html>");

        // Print a success message
        out.print("Success! To view html files go to: " + fileIndex.name() + ".");

        //Close the fileIndex, SimpleReader, and SimpleWriter
        fileIndex.close();
        in.close();
        out.close();
    }
}
